version: '2.4'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./book_my_ticket:/usr/src/app
    ports:
      - "80:80"
    entrypoint: "python manage.py runserver 0.0.0.0:80"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: library/postgres:latest
    env_file:
      - .env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pgdata:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    healthcheck:
      test: "exit 0"

volumes:
  pgdata:

