from django.urls import path, re_path
from .views import (
    CityList,
    CityDetail,
    BrandList,
    BrandDetail,
    CinemaList,
    CinemaDetail,
    ScreenList,
    ScreenDetail,
    MovieList,
    MovieDetail,
    SeatCategoryList,
    SeatCategoryDetail,
    MoviesByCity,
    ShowtimeList,
    CinemaByMovie,
    ScreenCapacityList,
    SeatAvailability,
    SeatBooking,
)


urlpatterns = [
    path("management/city/", CityList.as_view()),
    path("management/city/<int:pk>/", CityDetail.as_view()),
    path("management/brand/", BrandList.as_view()),
    path("management/brand/<int:pk>/", BrandDetail.as_view()),
    path("management/cinema/", CinemaList.as_view()),
    path("management/cinema/<int:pk>/", CinemaDetail.as_view()),
    path("management/screen/", ScreenList.as_view()),
    path("management/screen/<int:pk>/", ScreenDetail.as_view()),
    path("management/screen_capacity", ScreenCapacityList.as_view()),
    path("management/movie/", MovieList.as_view()),
    path("management/movie/<int:pk>/", MovieDetail.as_view()),
    path("management/seat_category/", SeatCategoryList.as_view()),
    path("management/seat_category/<int:pk>/", SeatCategoryDetail.as_view()),
    path("management/showtime/", ShowtimeList.as_view()),
    path("movies_by_city/", MoviesByCity.as_view(), name="movies_by_city"),
    path("cinema_by_movie/", CinemaByMovie.as_view()),
    re_path(
        r"^check_seat_availability/(?P<showtime_id>[0-9]+)/$",
        SeatAvailability.as_view(),
    ),
    path("book_my_seat/", SeatBooking.as_view()),
]
